"""Initial migration

Revision ID: 93671fcbae56
Revises: 
Create Date: 2026-06-10 13:11:02.631213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93671fcbae56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted for SQLite ###
    # If the table does not exist, create it. If it exists, skip creation.
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'apprentice' not in inspector.get_table_names():
        op.create_table(
            'apprentice',
            sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
            sa.Column('created_by', sa.Integer(), nullable=False),
            sa.Column('student_user_id', sa.Integer(), nullable=True),
            sa.Column('group_number', sa.String(length=30), nullable=False),
            sa.Column('document_type', sa.String(length=30), nullable=False),
            sa.Column('document_number', sa.String(length=30), nullable=False),
            sa.Column('first_names', sa.String(length=120), nullable=False),
            sa.Column('last_names', sa.String(length=120), nullable=False),
            sa.Column('gender', sa.String(length=20), nullable=True),
            sa.Column('phone', sa.String(length=30), nullable=True),
            sa.Column('email', sa.String(length=150), nullable=True),
            sa.Column('municipality_origin', sa.String(length=120), nullable=True),
            sa.Column('program_name', sa.String(length=150), nullable=True),
            sa.Column('group_validity', sa.String(length=80), nullable=True),
            sa.Column('lead_instructor', sa.String(length=150), nullable=True),
            sa.Column('followup_instructor', sa.String(length=150), nullable=True),
            sa.Column('ep_modality', sa.String(length=120), nullable=True),
            sa.Column('sofia_status', sa.String(length=80), nullable=True),
            sa.Column('practice_start_date', sa.String(length=40), nullable=True),
            sa.Column('practice_end_date', sa.String(length=40), nullable=True),
            sa.Column('company_name', sa.String(length=150), nullable=True),
            sa.Column('company_municipality', sa.String(length=120), nullable=True),
            sa.Column('company_address', sa.String(length=180), nullable=True),
            sa.Column('coformador_name', sa.String(length=150), nullable=True),
            sa.Column('coformador_email', sa.String(length=150), nullable=True),
            sa.Column('coformador_phone', sa.String(length=30), nullable=True),
            sa.Column('arl_responsible', sa.String(length=150), nullable=True),
            sa.Column('individual_management', sa.Text(), nullable=True),
            sa.Column('followup_moments', sa.String(length=120), nullable=True),
            sa.Column('evaluation_date', sa.String(length=40), nullable=True),
            sa.Column('english_results', sa.String(length=120), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('followup_instructor_email', sa.String(length=150), nullable=True),
            sa.Column('program_level', sa.String(length=80), nullable=True),
            sa.Column('group_id', sa.Integer(), nullable=True),
            sa.Column('followup_moment1_start', sa.String(length=40), nullable=True),
            sa.Column('followup_moment1_end', sa.String(length=40), nullable=True),
            sa.Column('followup_moment2_start', sa.String(length=40), nullable=True),
            sa.Column('followup_moment2_end', sa.String(length=40), nullable=True),
            sa.Column('followup_moment3_start', sa.String(length=40), nullable=True),
            sa.Column('followup_moment3_end', sa.String(length=40), nullable=True),
            sa.Column('followup_moment4_start', sa.String(length=40), nullable=True),
            sa.Column('followup_moment4_end', sa.String(length=40), nullable=True),
            sa.Column('continues_company', sa.String(length=30), nullable=True),
            sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='fk_apprentice_created_by_user'),
            sa.ForeignKeyConstraint(['student_user_id'], ['user.id'], name='fk_apprentice_student_user_id_user'),
            sa.UniqueConstraint('document_number', name='uq_apprentice_document_number'),
        )

    # Ensure indexes exist (idempotent)
    op.create_index('ix_apprentice_document_number', 'apprentice', ['document_number'], unique=True)
    op.create_index('ix_apprentice_group_id', 'apprentice', ['group_id'], unique=False)
    op.create_index('ix_apprentice_group_number', 'apprentice', ['group_number'], unique=False)

    # training_group index (create if table exists)
    if 'training_group' in inspector.get_table_names():
        op.create_index('ix_training_group_group_number', 'training_group', ['group_number'], unique=True)

    # If you need to change column types/lengths on SQLite, use batch_alter_table.
    # Here we attempt to alter followup_moments length only if necessary.
    # Note: SQLite requires table recreation; batch_alter_table handles it.
    with op.batch_alter_table('apprentice', schema=None) as batch_op:
        # Only attempt to alter if column exists; batch_op.alter_column is safe if types match
        try:
            batch_op.alter_column(
                'followup_moments',
                existing_type=sa.String(length=120),
                type_=sa.String(length=200),
                existing_nullable=True
            )
        except Exception:
            # If alteration fails on SQLite, skip here; the table will remain with previous length.
            pass
    # ### end Alembic commands ###


def downgrade():
    # Drop indexes and constraints created above (idempotent)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'apprentice' in inspector.get_table_names():
        try:
            op.drop_constraint('fk_apprentice_group_id_training_group', 'apprentice', type_='foreignkey')
        except Exception:
            pass
        try:
            op.drop_index('ix_apprentice_group_number', table_name='apprentice')
        except Exception:
            pass
        try:
            op.drop_index('ix_apprentice_group_id', table_name='apprentice')
        except Exception:
            pass
        try:
            op.drop_index('ix_apprentice_document_number', table_name='apprentice')
        except Exception:
            pass

    if 'training_group' in inspector.get_table_names():
        try:
            op.drop_index('ix_training_group_group_number', table_name='training_group')
        except Exception:
            pass

    # Revert column alteration if possible
    with op.batch_alter_table('apprentice', schema=None) as batch_op:
        try:
            batch_op.alter_column(
                'followup_moments',
                existing_type=sa.String(length=200),
                type_=sa.String(length=120),
                existing_nullable=True
            )
        except Exception:
            pass
