from __future__ import annotations

from flask import Blueprint, redirect, render_template, url_for, request
from flask_login import current_user, login_required

from extensions import db
from models.notification import Notification

notifications_bp = Blueprint("notifications", __name__, url_prefix="/notifications")


@notifications_bp.get("/")
@login_required
def index():
    notifications = (
        Notification.query.filter_by(user_id=current_user.id)
        .order_by(Notification.created_at.desc())
        .limit(50)
        .all()
    )
    return render_template("notifications/index.html", notifications=notifications)


@notifications_bp.post("/<int:notification_id>/read")
@login_required
def mark_read(notification_id: int):
    notification = Notification.query.filter_by(
        id=notification_id,
        user_id=current_user.id,
    ).first_or_404()
    notification.mark_read()
    db.session.commit()
    return redirect(request.referrer or url_for("notifications.index"))


@notifications_bp.post("/mark-all-read")
@login_required
def mark_all_read():
    notifications = Notification.query.filter_by(
        user_id=current_user.id,
        is_read=False,
    ).all()
    for notification in notifications:
        notification.mark_read()
    db.session.commit()
    return redirect(request.referrer or url_for("notifications.index"))


@notifications_bp.get("/<int:notification_id>/open")
@login_required
def open_notification(notification_id: int):
    """Mark a notification as read and follow its stored application URL."""
    notification = Notification.query.filter_by(
        id=notification_id,
        user_id=current_user.id,
    ).first_or_404()
    notification.mark_read()
    target = notification.url or url_for("notifications.index")
    # All URLs currently generated by GIA are application-relative. Fall back
    # to the notification list for any unexpected external value.
    if not target.startswith("/"):
        target = url_for("notifications.index")
    db.session.commit()
    return redirect(target)
